name: Check links
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.1.0
        with:
          fail: true
